-- =====================================================
-- CCMS AI Judgment Extractor - Database Schema
-- Author: Tanya
-- Branch: database
-- Description: Core tables for the Court Case
-- Monitoring System. Stores judgment details,
-- AI extracted actions, human review audit trail,
-- and raw Claude API responses.
-- =====================================================


-- Cases table
-- Stores core judgment metadata fetched from
-- High Court CIS via API in PDF format.
-- Each case maps to one uploaded judgment PDF.
CREATE TABLE cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number TEXT NOT NULL UNIQUE,
  parties_involved TEXT,
  next_hearing_date DATE,
  judge_name TEXT,
  legal_sections TEXT[],  -- e.g. {IPC 302, CrPC 482}
  summary TEXT,           -- plain english summary generated by Claude
  pdf_url TEXT,           -- path to judgment PDF stored in Supabase storage
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Actions table
-- Stores AI extracted directives from each judgment.
-- Each action belongs to one case and tracks
-- human review status (pending/approved/rejected).
-- bbox columns store PDF coordinates so the
-- review UI can highlight the source text.
CREATE TABLE actions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES cases(id) ON DELETE CASCADE,
  department TEXT,              -- responsible govt department
  action_required TEXT,         -- what the court directed
  deadline DATE,                -- compliance deadline
  priority TEXT CHECK (priority IN ('high', 'medium', 'low')),
  confidence_score FLOAT CHECK (confidence_score BETWEEN 0 AND 1),
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  bbox_page INT,                -- PDF page number of extracted text
  bbox_x0 FLOAT, bbox_y0 FLOAT, -- top-left coordinates of highlight
  bbox_x1 FLOAT, bbox_y1 FLOAT, -- bottom-right coordinates of highlight
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- AI Responses table
-- Stores raw Claude API responses per case.
-- Used for debugging extraction issues and
-- improving prompts across versions.
CREATE TABLE ai_responses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id UUID REFERENCES cases(id) ON DELETE CASCADE,
  raw_response JSONB,    -- full Claude response stored as JSON
  prompt_version TEXT,   -- tracks which prompt version was used
  model_used TEXT,       -- e.g. claude-sonnet-4-20250514
  created_at TIMESTAMPTZ DEFAULT now()
);
-- Audit Logs table
-- Maintains legally sound trail of every human
-- reviewer action — approve, edit, reject.
-- Stores before/after state for full traceability.
CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  table_name TEXT NOT NULL,   -- which table was modified
  record_id UUID NOT NULL,    -- which record was modified
  action_type TEXT CHECK (action_type IN (
    'Approved', 'Rejected', 'Edited',
    'Status Update', 'Created', 'Deleted'
  )),
  previous_state JSONB,  -- snapshot before change
  new_state JSONB,       -- snapshot after change
  updated_by TEXT,       -- reviewer user ID
  comments TEXT,         -- optional reviewer notes
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Auto updates updated_at timestamp on actions table
-- whenever a reviewer edits or approves a record.
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON actions
FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- Row Level Security enabled on all tables.
-- Policies set to allow_all for hackathon demo.
-- Should be locked down per user role in production.
ALTER TABLE cases ENABLE ROW LEVEL SECURITY;
ALTER TABLE actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_all" ON cases FOR ALL USING (true);
CREATE POLICY "allow_all" ON actions FOR ALL USING (true);
CREATE POLICY "allow_all" ON ai_responses FOR ALL USING (true);
CREATE POLICY "allow_all" ON audit_logs FOR ALL USING (true);

-- Indexes on foreign keys for faster joins.
-- Important when cases table grows to 1000+ records.
CREATE INDEX idx_actions_case_id ON actions(case_id);
CREATE INDEX idx_ai_responses_case_id ON ai_responses(case_id);
CREATE INDEX idx_audit_logs_record_id ON audit_logs(record_id);
CREATE INDEX idx_audit_logs_table_name ON audit_logs(table_name);
